// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Products = sequelize.define('products', {
    title: {
      type: DataTypes.STRING,
    },
    description: {
      type: DataTypes.STRING,
    },
    instructions: {
      type: DataTypes.STRING,
    },
    ingredients: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: "{}",
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    allergens: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      defaultValue: "{}",
    },
    productType: {
      type: DataTypes.INTEGER,
    },
    imageFileName: {
      type: DataTypes.STRING,
    },
    imageContentType: {
      type: DataTypes.STRING,
    },
    imageFileSize: {
      type: DataTypes.INTEGER,
    },
    imageUpdatedAt: {
      type: DataTypes.DATE,
    },
    price: {
      type: DataTypes.DOUBLE,
      defaultValue: 0.0,
    },
  }, {
    tableName: 'products',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Products.associate = (models) => {
  };

  return Products;
};
